basic service discovery
cisco-open/nasp pull request #41
Opened 2023-11-14 10:32 UTC by waynz0r

## Description

basic service discovery support

## Type of Change

- [ ] Bug Fix
- [x] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

2023-11-15 08:09 UTC, bonifaido requested changes
I would add some pointers to the README how to start the agent to fill SD info.

2023-11-16 14:02 UTC, bonifaido approved these changes

2023-11-16 14:16 UTC, baluchicken approved these changes

2023-11-24 12:30 UTC, baluchicken approved these changes

2023-11-24 12:47 UTC, merged